# FASTAPI CONFIG

HOST: str = "0.0.0.0"
PORT: int = 8000

RELOAD_APP: bool = True # Developers Only

# DETA CONFIG

DETA_BASE_NAME: str = "DETA-BASE-NAME-HERE"

DETA_PROJECT_KEY: str = "DETA-PROJECT-KEY-HERE"
DETA_PROJECT_ID: str = "DETA-PROJECT-ID-HERE"
